### ISSUE TITLE
Replace MACHINE with PLATFORM keywords for consistency

### ISSUE THREAD

**Issue by physicalist** [borismarin/genesis2.4gamma#12]
Introduce `PLATFORM=uname -s` to replace MACHINE keyword in all sub-makefiles;
re-use `MACHINE=uname -m` to determine endianness in cases where `uname -p` returns "unknown" on some architecture/OS combinations

**Comment by dbeeman** [comment]
I would like to avoid messing with the lower level Makefiles as much as possible. I worry that we might breaks something or lose compatibility with previous usage - not to mention changing a lot
of READMEs.  Is there another way around this?

**Comment by physicalist** [comment]
The workaround is to not change it, as you said. If we really want to make sure endianness detection works in all cases, we could use any other free keyword assigned to `uname -m`, maybe simply use `PLATFORM=uname -m` for that check (even if it's logically incoherent) :)
