### ISSUE TITLE
Confirm TERMCAP & TERMOPTS for other platforms

### ISSUE THREAD

**Issue by physicalist** [borismarin/genesis2.4gamma#13]
GDB has their own autoconf logic to determine TERMCAP & TERMOPTS parameters (i.e., go with (n)curses if available, down to the original termcap library as fallback or on legacy systems), we could integrate that - maybe that's too much hassle for too little gain, though?

**Comment by dbeeman** [comment]
I would leave that as a low priority, it may not be worth the hassle. The advantage of having the old Makefile.dist, and others exist along with autoconf is that users of legacy systems without ncurses can always go back to the old Makefile.dist sections.

**Comment by physicalist** [comment]
I agree, not worth it.
