### ISSUE TITLE
generating nxgenesis with autoconf

### ISSUE THREAD

**Issue by dbeeman** [borismarin/genesis2.4gamma#15]
How would autoconf be used to generate nxgenesis (no Xodus libs)? People who use
GENESIS or PGENESIS on remote supercomputers will use nxgenesis.

**Comment by physicalist** [comment]
We could probably integrate it with a flag like --without-X to the configure script
Otherwise, make nxgenesis should work as per usual I assume (haven't tested yet)

**Comment by borismarin** [comment]
```
make nxgenesis
```

 is working fine for me under both linux and osx

**Comment by borismarin** [comment]
See #21 as well.
