### ISSUE TITLE
problematic X includes and libs for osx

### ISSUE THREAD

**Issue by borismarin** [borismarin/genesis2.4gamma#2]
the XLIB and XINCLUDE macros are being detected correctly by autoconf, but -L -I starting with std /usr locations are breaking the build for OSX

**Comment by borismarin** [comment]
fixed with  c1027ad6efda7ca4c19c1bdfe24e3021b296be94
Should move logic to configure.ac, though...

**Comment by physicalist** [comment]
Have you tried again to fix this in autoconf directly? Why should @X_LIB@ ever be empty, anyway, if autoconf detects it correctly?

**Comment by borismarin** [comment]
X_LIB is detected as empty (which is correct) e.g. for Debian/Ubuntu. This was a q&d workaround, feel free to improve it!
