### ISSUE TITLE
convert tool filename conflicts with ImageMagick's convert, rename?

### ISSUE THREAD

**Issue by physicalist** [borismarin/genesis2.4gamma#27]
Genesis' `convert` tool in `/path/to/genesis/bin/convert` conflicts with the `convert` utility from ImageMagick, which is installed on many a popular Linux distribution. Maybe we should consider renaming it to `genconvert` instead, and/or not build it by default?

**Comment by dbeeman** [comment]
See my comment to issue #28. The convert utility is old and not likely to be used, It should remain out of the search path. It should have been named genconvert, but too many documents would need to be changed to do it now.  No one is likely to want to convert 20 year old GENESIS 1 scripts, so let's leave it safely buried in genesis/bin.

**Comment by physicalist** [comment]
Fair enough.
One could technically prevent convert to be built in the first place and give it its own make rule, but again, that would imply having to rewrite & test Makefiles and READMEs. Not something to bother you with at this point :)
-> CLOSED.
