### ISSUE TITLE
Binary paths should follow standards

### ISSUE THREAD

**Issue by physicalist** [borismarin/genesis2.4gamma#28]
Currently, the genesis binary is installed directly to `$PREFIX/` when it should be `$PREFIX/bin/`. `convert`, on the other hand, is correctly installed into `$PREFIX/bin/`. This is inconsistent and doesn't follow the [FHS](http://tldp.org/LDP/Linux-Filesystem-Hierarchy/html/index.html) (but actually we'd have to significantly rewrite the Makefiles to follow that document...).
My point is rather, if I wanted to have all of genesis' binaries in my PATH environment variable, I'd have to include several directories, not just e.g. `/usr/local/genesis/bin`. We could either change the target directory for that or symlink it into bin after it is built.

NB: `convert`'s name is actually conflicting with another popular tool, see #27.

**Comment by dbeeman** [comment]
At this late date, I don't want to make any big changes from conventions that were used in past releases. I would like  the genesis executable to remain in genesis-2.4/genesis. The conflict of genesis/bin/convert with ImageMagick convert was annoying when I discovered it a few years ago, but keeping it out of the normal search path keeps it from being a problem.  In fact, I doubt it is ever used anymore.  It was designed to convert old GENESIS 1 scripts to GENESIS 2 when GENESIS 2.0 was first released. I think that keeping it safely where it is is best.  Also, I don't want to do all that editing of the Hyperdoc manual.

**Comment by physicalist** [comment]
Fair enough.

I'm writing a formula for [Homebrew](http://brew.sh) to automatically install GENESIS on OSX, but I simply added a local patch to the formula itself to avoid the name conflict (which prevented proper installation). So when installed with Homebrew on OSX, both binaries now end up in `$PREFIX/bin`, and `convert` is renamed to `genconvert`. But that doesn't affect manual installations, the README (there's a prominent _"Caveat"_ notice when installing, or "brewing" in Homebrew lingo, which users of that package manager should be used to), or anything else really. So I declare this issue CLOSED.
