### ISSUE TITLE
Verified platforms

### ISSUE THREAD

**Issue by borismarin** [borismarin/genesis2.4gamma#9]
# Supported platforms
- [x] OSX Mavericks (intel)
- [x] OSX Mountain Lion (intel)
- [x] Debian wheezy (amd64)
- [x] Ubuntu Saucy (amd64)
- [x] Ubuntu Utopic (amd64)

**Comment by borismarin** [comment]
see #21 for automated tests on linux (both clang and gcc working)

**Comment by physicalist** [comment]
Confirmed to compile on OSX (Intel x86_64) with 2ececad701cbc8696eb3d93bd6279663b9bd427b with all three of
- cc - Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
- gcc - Apple LLVM version 6.0 (clang-600.0.54) (based on LLVM 3.5svn)
- gcc - version 4.9.1 (Homebrew gcc 4.9.1)
